name: GitHub release

on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies 
        run: docker-compose run github-release npm i 

      - name: Install puppeteer
        run: docker-compose run github-release node node_modules/puppeteer/install.js

      - name: Docker build
        run: docker-compose run github-release node ./screenshoot.js

      # - name: Permissions
      #   run: sudo chmod 1000:1000 ./src/*.png

      - name: Create release
        run: gh release create v$( date +%Y-%m-%d-%H-%M ) ./src/app/*.png
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
